version: '2'

vars:
  NAME: alertmanager-sentry-gateway
  VERSION: 0.5.3
  COMMIT: {sh: git rev-parse --verify HEAD}
  BUILD_FLAGS: -ldflags "-X main.VERSION={{.VERSION}} -X main.COMMIT={{.COMMIT}}"

tasks:
  build:
    cmds:
      - go build .
  test:
    cmds:
      - go vet ./...
      - go test -v -coverprofile=cover.out ./...
  cover:
    deps: [test]
    cmds:
      - go tool cover -html=cover.out
  package:
    cmds:
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build {{.BUILD_FLAGS}} .
      - tar -czf dist/{{.NAME}}_{{.OS}}_{{.ARCH}}.tar.gz {{.NAME}}
      - rm -rf {{.NAME}}
  dist:
    deps: [test]
    cmds:
      - mkdir -p dist
      - task: package
        vars: {OS: "linux", ARCH: "amd64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm"}
      - task: package
        vars: {OS: "darwin", ARCH: "amd64"}
  container:
    deps: [test]
    cmds:
      - docker build -t summerwind/{{.NAME}}:latest -t summerwind/{{.NAME}}:{{.VERSION}} 
          --build-arg BUILD_FLAGS='{{.BUILD_FLAGS}}' .
  vendor:
    cmds:
      - go mod tidy
      - go mod vendor
  clean:
    cmds:
      - rm -rf {{.NAME}} dist cover.out
